
# (C) 2023 Jack Lloyd
# (C) 2023 Fabian Albert, Rohde & Schwarz Cybersecurity
#
# Botan is released under the Simplified BSD License (see license.txt)

name: tls-anvil

permissions:
  contents: read

on:
  push:
     branches: [ master, ci/tls-anvil ] # !!!TODO!!! remove me!!!
  pull_request:
     branches: [ master ]

jobs:
  tls_anvil:
    name: "TLS-Anvil - Botan Server Test"

    runs-on: ubuntu-22.04

    steps:
      - name: Fetch Botan Repository
        uses: actions/checkout@v3

      - name: Setup Build Agent
        uses: ./.github/actions/setup-build-agent
        with:
          target: static
          cache-key: linux-clang-x86_64-static

      - name: Build Botan
        run: ./configure.py --compiler-cache=ccache --build-targets=static,cli --without-documentation && make -j8

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Fetch TLS-Anvil fork for Botan tests
        uses: actions/checkout@v3
        with:
          repository: FAlbertDev/TLS-Anvil
          path: ./tlsanvil

      - name: Build TLS-Anvil
        working-directory: ./tlsanvil/
        run: mvn install -DskipTests -Dspotless.apply.skip

      - name: Test Botan Server with TLS-Anvil
        run: python3 ./src/scripts/ci/ci_tlsanvil_test.py --server-test ./botan ./tlsanvil/TLS-Testsuite/apps/TLS-Testsuite.jar
        env:
          DOCKER: 1 # TLS-Anvil specific to disable the loading bar

      - uses: actions/upload-artifact@v3
        with:
          name: tls-anvil-server-test-results
          path: |
            ./TestSuiteResults/
            ./logs/

      - name: Check TLS-Anvil Test Results
        run: python3 ./src/scripts/ci/ci_tlsanvil_check.py --verbose ./TestSuiteResults
